config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "projects#index"
  resources :projects,  only: [:index, :new, :create, :show] do
    resources :tasks, only: [:new, :create, :show] do
      resources :comments, only: [:new, :create]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_users
  has_many :users, through: :project_users
  has_many :tasks

  validates :title, presence: true
  validates :goal,  presence: true
  validates :date,  presence: true
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :comments

  validates :title,   presence: true
  validates :aim,     presence: true
  validates :date,    presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英字と半角数字それぞれを含めて設定してください' }

  has_many :project_users
  has_many :projects, through: :project_users
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @comment = Comment.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
    @comment = @task.comments.new(com_params)
    if @comment.save
      redirect_to project_task_path(@project, @task)
    else
      puts @comment.errors.full_messages
      render 'new'
    end
  end

  private

  def com_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(pj_params.except(:user_ids))

    if @project.save
      user_ids = pj_params[:user_ids]
      user_ids.each do |user_id|
        ProjectUser.create(project_id: @project.id, user_id:)
      end
      redirect_to root_path
    else
      puts @project.errors.full_messages
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def pj_params
    params.require(:project).permit(:title, :goal, :date, user_ids: [])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.new(tk_params)
    if @task.save
      redirect_to root_path
    else
      puts @task.errors.full_messages
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
  end

  private

  def tk_params
    params.require(:task).permit(:title, :aim, :date, :content).merge(project_id: params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/comments/new.html.erb
<%= render "shared/header" %>

<div class="comment_form">
<%=form_with model: [@project, @task, @comment],url:project_task_comments_path, local: true do |f|%>
  <div class="comment_user">
    ユーザー名：
  <%= current_user.name %>
  </div>
<div class="comment_content_form">
<%= f.text_area :comment ,class:"comment_content", placeholder:"コメントやフィードバックを記入してください"%>
</div>

<%= f.submit "コメント/フィードバックする", class:"comment_btn"%>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freedwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<%= render "shared/header" %>

<div class="project_index">

  <div class="side_bar">
    <div class="chat_gene_box">
      <%= link_to "新規プロジェクトの作成", new_project_path, class:"chat_gene"%>
    </div>  
    <div class="side_bar_title">
      プロジェクト一覧
    </div>

    <div class="pj_lists">
    <% current_user.projects.each do |project| %>
      <div class="pj_list">
        <div class="pj_name">
          <%= link_to project.title, project_path(project.id), class:"pj_name" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <div class="task_index">
  </div> 
  
</div>

app/views/projects/new.html.erb
<%= render "shared/header" %>

<div class="pj_gene_page">
  <div class="pj_gene_page_box">
    <div class="pj_gene_page_title">プロジェクト作成ページ</div>
    <div class="pj_gene_form">
      <%=form_with model: @project, local: true do |f|%>
      <div class="pj_title_label">
        <label>プロジェクト名</label>
      </div>
      <%= f.text_field :title, class: 'pj_title', placeholder:"プロジェクト名を記入してください" %>

      <div class="pj_goal_label">
          <label>プロジェクト目標</label>
      </div>
      <%= f.text_field :goal, class: 'pj_goal', placeholder:"プロジェクト目標を記入してください" %>

      <div class="pj_date">
        <label>完工予定日：</label>
        <%= f.date_select :date, class: 'pj_date', placeholder:"完工予定日を入力してください",use_two_digit_numbers:true %>
      </div>
      <div class="pj_member_label">
        <label>プロジェクトメンバー</label>
      </div>
      <select name="project[user_ids][]" multiple >
        <option value="">チャットするユーザーを選択してください</option>
        <% User.where.not(id: current_user.id).each do |user| %>
          <option value=<%= user.id %>><%= user.name %></option>
        <% end %>
      </select>
      <input name="project[user_ids][]" type="hidden" value=<%= current_user.id %>>
      
      <%= f.submit "作成する", class:"pj_gene_btn"%>
    </div> 
  </div>
</div>

<% end %>

app/views/projects/show.html.erb
<%= render "shared/header" %>

<div class="show_layout">
  <div class="project_show">
        <div class="pj_show_list">
          <div class="pj_show">
            <div class="pj_show_title">  
              プロジェクト名：
              <%= @project.title %>
            </div>
            <div class="pj_show_goal">
              プロジェクト目標：
              <%= @project.goal %>
            </div>
            <div class="pj_show_date">
              完工予定日：
              <%= @project.date %>
            </div>
          </div>
        </div>
        <div class="task_lists">
          <div class= "task_lists_label">
            タスク一覧
          </div>
          <div class= "task_list">
            <% @project.tasks.each do |task| %>
            <div class= "tasks">
              <div class="tasks_title">名称：<%=link_to task.title, project_task_path(@project, task) %></div>
              <div class="tasks_aim">目標/ねらい：<%= task.aim %></div>
              <div class="tasks_date">実施日：<%= task.date %></div>
            </div>
            <% end %>

          </div>

        </div> 
  </div>
  <div class="show_side" >
    <div class="task_new_link">
      <%= link_to "タスク作成", new_project_task_path(params[:id]),class:"task_new_name" %>
    </div>  
  </div>
</div>

app/views/shared/_header.html.erb
<header class="app_header">
  <div class="logo_header">
    <div>
      <%= link_to "Freed Work", root_path, class: "logo_freedwork"%>
    </div>
    <div class="header_username" >
      <%= current_user.name %>
      <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class:'header_logout_btn'%>
    </div>
  </div>
</header>

app/views/tasks/new.html.erb
<%= render "shared/header" %>

<div class="task_gene_page">
  <div class="task_gene_page_box">
    <div class="task_gene_page_title">
      <%= @project.title %>/タスク作成ページ
      <%=form_with model: [@project, @task], url: project_tasks_path, local: true do |f|%>
    </div>
    <div class="task_gene_form">
        <div class="task_title_label">
          <label>タスク名</label>
        </div>
        <%= f.text_field :title, class: 'task_title', placeholder:"タスク名を記入してください" %>

        <div class="task_aim_label">
            <label>目標</label>
        </div>
        <%= f.text_field :aim, class: 'task_aim', placeholder:"このタスクの目標/狙いを記入してください" %>

        <div class="task_date">
          <label>実施日：</label>
          <%= f.date_select :date, class: 'task_date', placeholder:"実施日を入力してください",use_two_digit_numbers:true %>
        </div>

        <div class="task_content_label">
          <label>内容</label>
          <%=f.text_area :content, class: 'task_content', placeholder:"タスクの内容、結果、考察を記入してください"%>
        </div>
        <%= f.submit "作成する", class:"task_gene_btn"%>
      <% end %>
    </div> 
  </div>
</div>

app/views/tasks/show.html.erb
<%= render "shared/header" %>
<div class="task_show_pjname">
<%= @project.title %>
</div>
<div class="task_show_tkname">
<%= @task.title %>
</div>

<div class="task_show_page">
  <div class="task_show_page_box">
    <div class="task_show_form">
      <div class="task_show_title_label">
        <label>タスク名</label>
      </div>
      <div class='task_show_title' >
        <%= @task.title %>
      </div>
      <div class="task_show_aim_label">
          <label>目標</label>
      </div>
      <div class="task_show_aim">
        <%= @task.aim %>
      </div>
      <div class="task_show_date_label">
        <label>実施日</label>
      </div>
      <div class="task_show_date">
        <%= @task.date %>
      </div>
      <div class="task_show_content_label">
        <label>内容</label>
      </div>
      <div class="task_show_content">
        <%= @task.content%>
      </div>
    </div>
  </div>
</div>

<div class="comment_page">
  <div class="comment_list">
   <% @task.comments.each do |comment| %>
      <div class="comment_username">
          <%= comment.user.name %>：
          <%= comment.comment %>
          <%= comment.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
      </div>
    <% end %>
  </div>
</div>

<div class= "comment_new_btn"> 
    <%= link_to "コメント/フィードバックする", new_project_task_comment_path(@project, @task), class:"comment_new_btn" %>
</div>